const f=()=>{
    try{
        let a=0
        console.log(program)
        console.log("Program ran successfully")
    }
    catch(err){
        console.log("This is an error")
        console.log(p)
    }
    
    finally{
        console.log("I am a good boy")
    }
}
f()